"""empty message

Revision ID: 05ed8bb95b86
Revises: a4e8854d720c
Create Date: 2019-04-29 20:23:50.984095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ed8bb95b86'
down_revision = 'a4e8854d720c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areasconocimiento',
    sa.Column('cod_area', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_area')
    )
    op.create_index(op.f('ix_areasconocimiento_nombre'), 'areasconocimiento', ['nombre'], unique=True)
    op.drop_index('ix_areas_nombre', table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('cod_area', sa.VARCHAR(length=64), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_area')
    )
    op.create_index('ix_areas_nombre', 'areas', ['nombre'], unique=1)
    op.drop_index(op.f('ix_areasconocimiento_nombre'), table_name='areasconocimiento')
    op.drop_table('areasconocimiento')
    # ### end Alembic commands ###
