"""empty message

Revision ID: 1b6f0ba7f250
Revises: 7a1e8462c648
Create Date: 2019-09-27 13:42:25.924348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6f0ba7f250'
down_revision = '7a1e8462c648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veniaII')
    op.drop_table('veniaI')
    op.drop_table('responsible_conflict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_conflict',
    sa.Column('area_cod', sa.VARCHAR(length=64), nullable=False),
    sa.Column('subject_cod', sa.VARCHAR(length=64), nullable=False),
    sa.Column('teacher_dni', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['subject_cod', 'area_cod'], ['subject.subject_cod', 'subject.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('area_cod', 'subject_cod', 'teacher_dni')
    )
    op.create_table('veniaI',
    sa.Column('area_cod', sa.VARCHAR(length=64), nullable=False),
    sa.Column('teacher_dni', sa.VARCHAR(length=64), nullable=False),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('rejected', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('approved IN (0, 1)'),
    sa.CheckConstraint('rejected IN (0, 1)'),
    sa.ForeignKeyConstraint(['area_cod'], ['knowledgeArea.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('area_cod', 'teacher_dni')
    )
    op.create_table('veniaII',
    sa.Column('area_cod', sa.VARCHAR(length=64), nullable=False),
    sa.Column('subject_cod', sa.VARCHAR(length=64), nullable=False),
    sa.Column('teacher_dni', sa.VARCHAR(length=64), nullable=False),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('rejected', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('approved IN (0, 1)'),
    sa.CheckConstraint('rejected IN (0, 1)'),
    sa.ForeignKeyConstraint(['subject_cod', 'area_cod'], ['subject.subject_cod', 'subject.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('area_cod', 'subject_cod', 'teacher_dni')
    )
    # ### end Alembic commands ###
