"""empty message

Revision ID: 3d2abe9cdd4c
Revises: 
Create Date: 2019-04-30 22:30:48.494277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2abe9cdd4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areaconocimiento',
    sa.Column('cod_area', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_area')
    )
    op.create_index(op.f('ix_areaconocimiento_nombre'), 'areaconocimiento', ['nombre'], unique=True)
    op.create_table('grupo',
    sa.Column('cod_grupo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_grupo')
    )
    op.create_table('profesor',
    sa.Column('DNI', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('apellidos', sa.String(length=64), nullable=True),
    sa.Column('tutorias', sa.String(length=140), nullable=True),
    sa.Column('potencial_docente', sa.String(length=64), nullable=True),
    sa.Column('horas_preasignadas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DNI')
    )
    op.create_table('titulacion',
    sa.Column('cod_titulacion', sa.Integer(), nullable=False),
    sa.Column('acronimo', sa.String(length=64), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('centro', sa.String(length=64), nullable=True),
    sa.Column('cod_plan', sa.String(length=64), nullable=True),
    sa.Column('cod_especial', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_titulacion')
    )
    op.create_index(op.f('ix_titulacion_acronimo'), 'titulacion', ['acronimo'], unique=True)
    op.create_index(op.f('ix_titulacion_nombre'), 'titulacion', ['nombre'], unique=True)
    op.create_table('asignatura',
    sa.Column('cod_asignatura', sa.Integer(), nullable=False),
    sa.Column('cod_titulacion', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('curso', sa.Integer(), nullable=True),
    sa.Column('cuatrimestre', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_titulacion'], ['titulacion.cod_titulacion'], ),
    sa.PrimaryKeyConstraint('cod_asignatura')
    )
    op.create_table('PDA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_asig', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=64), nullable=True),
    sa.Column('observaciones', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_asig'], ['asignatura.cod_asignatura'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_asig')
    )
    op.create_table('Tiene',
    sa.Column('cod_asignatura', sa.Integer(), nullable=True),
    sa.Column('cod_area', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_area'], ['areaconocimiento.cod_area'], ),
    sa.ForeignKeyConstraint(['cod_asignatura'], ['asignatura.cod_asignatura'], )
    )
    op.create_table('asignado',
    sa.Column('cod_grupo', sa.Integer(), nullable=False),
    sa.Column('cod_asignatura', sa.Integer(), nullable=False),
    sa.Column('num_horas', sa.Integer(), nullable=True),
    sa.Column('horario', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['cod_asignatura'], ['asignatura.cod_asignatura'], ),
    sa.ForeignKeyConstraint(['cod_grupo'], ['grupo.cod_grupo'], ),
    sa.PrimaryKeyConstraint('cod_grupo', 'cod_asignatura')
    )
    op.create_table('imparte',
    sa.Column('DNI', sa.String(length=64), nullable=False),
    sa.Column('cod_grupo', sa.Integer(), nullable=False),
    sa.Column('cod_asignatura', sa.Integer(), nullable=False),
    sa.Column('coor_asignatura', sa.Boolean(), nullable=True),
    sa.Column('respon_practica', sa.Boolean(), nullable=True),
    sa.Column('venia', sa.Boolean(), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['DNI'], ['profesor.DNI'], ),
    sa.ForeignKeyConstraint(['cod_grupo', 'cod_asignatura'], ['asignado.cod_grupo', 'asignado.cod_asignatura'], ),
    sa.PrimaryKeyConstraint('DNI', 'cod_grupo', 'cod_asignatura')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imparte')
    op.drop_table('asignado')
    op.drop_table('Tiene')
    op.drop_table('PDA')
    op.drop_table('asignatura')
    op.drop_index(op.f('ix_titulacion_nombre'), table_name='titulacion')
    op.drop_index(op.f('ix_titulacion_acronimo'), table_name='titulacion')
    op.drop_table('titulacion')
    op.drop_table('profesor')
    op.drop_table('grupo')
    op.drop_index(op.f('ix_areaconocimiento_nombre'), table_name='areaconocimiento')
    op.drop_table('areaconocimiento')
    # ### end Alembic commands ###
