"""empty message

Revision ID: 53410fc4979d
Revises: 
Create Date: 2019-06-22 01:31:37.285023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53410fc4979d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgeArea',
    sa.Column('area_cod', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('area_cod')
    )
    op.create_index(op.f('ix_knowledgeArea_name'), 'knowledgeArea', ['name'], unique=True)
    op.create_table('universityDegree',
    sa.Column('university_degree_cod', sa.String(length=64), nullable=False),
    sa.Column('acronym', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('study_center', sa.String(length=64), nullable=True),
    sa.Column('plan_cod', sa.String(length=64), nullable=True),
    sa.Column('special_cod', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('university_degree_cod')
    )
    op.create_index(op.f('ix_universityDegree_acronym'), 'universityDegree', ['acronym'], unique=True)
    op.create_index(op.f('ix_universityDegree_name'), 'universityDegree', ['name'], unique=True)
    op.create_table('subject',
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('university_degree_cod', sa.String(length=64), nullable=False),
    sa.Column('academic_year', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('semester', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['university_degree_cod'], ['universityDegree.university_degree_cod'], ),
    sa.PrimaryKeyConstraint('subject_cod')
    )
    op.create_table('teacher',
    sa.Column('dni', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surnames', sa.String(length=64), nullable=True),
    sa.Column('tutorial', sa.String(length=140), nullable=True),
    sa.Column('potential', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['area_cod'], ['knowledgeArea.area_cod'], ),
    sa.PrimaryKeyConstraint('dni')
    )
    op.create_table('PDA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_cod', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('observations', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['subject_cod'], ['subject.subject_cod'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_cod')
    )
    op.create_table('Venia',
    sa.Column('area_cod', sa.String(length=64), nullable=True),
    sa.Column('teacher_dni', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['area_cod'], ['knowledgeArea.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], )
    )
    op.create_table('coordinator',
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=False),
    sa.Column('practice_coor', sa.Boolean(), nullable=True),
    sa.Column('subject_coor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subject_cod'], ['subject.subject_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('subject_cod', 'teacher_dni')
    )
    op.create_table('group',
    sa.Column('group_cod', sa.String(length=64), nullable=False),
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('hours', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['area_cod'], ['knowledgeArea.area_cod'], ),
    sa.ForeignKeyConstraint(['subject_cod'], ['subject.subject_cod'], ),
    sa.PrimaryKeyConstraint('group_cod', 'subject_cod', 'area_cod')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    op.drop_table('coordinator')
    op.drop_table('Venia')
    op.drop_table('PDA')
    op.drop_table('teacher')
    op.drop_table('subject')
    op.drop_index(op.f('ix_universityDegree_name'), table_name='universityDegree')
    op.drop_index(op.f('ix_universityDegree_acronym'), table_name='universityDegree')
    op.drop_table('universityDegree')
    op.drop_index(op.f('ix_knowledgeArea_name'), table_name='knowledgeArea')
    op.drop_table('knowledgeArea')
    # ### end Alembic commands ###
