"""empty message

Revision ID: 7b67b4edcbc0
Revises: bc5603c98ce1
Create Date: 2019-09-16 21:21:26.073621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b67b4edcbc0'
down_revision = 'bc5603c98ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsibleConflict',
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['subject_cod', 'area_cod'], ['subject.subject_cod', 'subject.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('area_cod', 'subject_cod', 'teacher_dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsibleConflict')
    # ### end Alembic commands ###
