"""empty message

Revision ID: 7ecdfc671a19
Revises: 5a103fa9f5b0
Create Date: 2019-07-19 23:31:00.711597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecdfc671a19'
down_revision = '5a103fa9f5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=64), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_user_teacher_dni'), 'user', ['teacher_dni'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_teacher_dni'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
