"""empty message

Revision ID: 860cad6f46bd
Revises: cf323b7f4507
Create Date: 2019-04-29 21:02:06.597496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860cad6f46bd'
down_revision = 'cf323b7f4507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_conocimiento',
    sa.Column('cod_area', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_area')
    )
    op.create_index(op.f('ix_area_conocimiento_nombre'), 'area_conocimiento', ['nombre'], unique=True)
    op.create_table('asignatura_profesor',
    sa.Column('cod_asig', sa.Integer(), nullable=True),
    sa.Column('dni', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_asig'], ['asignatura.cod_asignatura'], ),
    sa.ForeignKeyConstraint(['dni'], ['profesor.DNI'], )
    )
    op.drop_index('ix_areasconocimiento_nombre', table_name='areasconocimiento')
    op.drop_table('areasconocimiento')
    op.drop_constraint(None, 'asignatura_area', type_='foreignkey')
    op.create_foreign_key(None, 'asignatura_area', 'area_conocimiento', ['cod_area'], ['cod_area'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asignatura_area', type_='foreignkey')
    op.create_foreign_key(None, 'asignatura_area', 'areasconocimiento', ['cod_area'], ['cod_area'])
    op.create_table('areasconocimiento',
    sa.Column('cod_area', sa.VARCHAR(length=64), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_area')
    )
    op.create_index('ix_areasconocimiento_nombre', 'areasconocimiento', ['nombre'], unique=1)
    op.drop_table('asignatura_profesor')
    op.drop_index(op.f('ix_area_conocimiento_nombre'), table_name='area_conocimiento')
    op.drop_table('area_conocimiento')
    # ### end Alembic commands ###
