"""empty message

Revision ID: 8a0334ba7322
Revises: 
Create Date: 2019-04-29 18:50:58.569685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0334ba7322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulacion',
    sa.Column('cod_titulacion', sa.Integer(), nullable=False),
    sa.Column('acronimo', sa.String(length=64), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('centro', sa.String(length=64), nullable=True),
    sa.Column('cod_plan', sa.String(length=64), nullable=True),
    sa.Column('cod_especial', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_titulacion')
    )
    op.create_index(op.f('ix_titulacion_acronimo'), 'titulacion', ['acronimo'], unique=True)
    op.create_index(op.f('ix_titulacion_nombre'), 'titulacion', ['nombre'], unique=True)
    op.create_table('asignatura',
    sa.Column('cod_asignatura', sa.Integer(), nullable=False),
    sa.Column('cod_titulacion', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('curso', sa.Integer(), nullable=True),
    sa.Column('cuatrimestre', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_titulacion'], ['titulacion.cod_titulacion'], ),
    sa.PrimaryKeyConstraint('cod_asignatura')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignatura')
    op.drop_index(op.f('ix_titulacion_nombre'), table_name='titulacion')
    op.drop_index(op.f('ix_titulacion_acronimo'), table_name='titulacion')
    op.drop_table('titulacion')
    # ### end Alembic commands ###
