"""empty message

Revision ID: a4e8854d720c
Revises: cd5d9355880f
Create Date: 2019-04-29 20:22:56.382350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e8854d720c'
down_revision = 'cd5d9355880f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grupos',
    sa.Column('cod_grupo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_grupo')
    )
    op.create_table('areas',
    sa.Column('cod_area', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_area')
    )
    op.create_index(op.f('ix_areas_nombre'), 'areas', ['nombre'], unique=True)
    op.create_table('profesor',
    sa.Column('DNI', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('apellidos', sa.String(length=64), nullable=True),
    sa.Column('tutorias', sa.String(length=140), nullable=True),
    sa.Column('potencial_docente', sa.String(length=64), nullable=True),
    sa.Column('horas_preasignadas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DNI')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesor')
    op.drop_index(op.f('ix_areas_nombre'), table_name='areas')
    op.drop_table('areas')
    op.drop_table('Grupos')
    # ### end Alembic commands ###
