"""empty message

Revision ID: c9791dbe1984
Revises: 17f6b41f5093
Create Date: 2019-06-27 14:23:32.339415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9791dbe1984'
down_revision = '17f6b41f5093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('tutorial_hours', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'tutorial_hours')
    # ### end Alembic commands ###
