"""empty message

Revision ID: cd5d9355880f
Revises: 8a0334ba7322
Create Date: 2019-04-29 19:42:07.625286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5d9355880f'
down_revision = '8a0334ba7322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PDA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_asig', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=64), nullable=True),
    sa.Column('observaciones', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_asig'], ['asignatura.cod_asignatura'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_asig')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PDA')
    # ### end Alembic commands ###
