"""empty message

Revision ID: cf323b7f4507
Revises: fcdf847f2b33
Create Date: 2019-04-29 20:42:28.907704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf323b7f4507'
down_revision = 'fcdf847f2b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo',
    sa.Column('cod_grupo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_grupo')
    )
    op.create_table('asignatura_grupo',
    sa.Column('cod_asig', sa.Integer(), nullable=True),
    sa.Column('cod_grupo', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_asig'], ['asignatura.cod_asignatura'], ),
    sa.ForeignKeyConstraint(['cod_grupo'], ['grupo.cod_grupo'], )
    )
    op.drop_table('Grupos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grupos',
    sa.Column('cod_grupo', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('cod_grupo')
    )
    op.drop_table('asignatura_grupo')
    op.drop_table('grupo')
    # ### end Alembic commands ###
