"""empty message

Revision ID: d186d350ee61
Revises: 
Create Date: 2019-07-27 15:57:50.108759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd186d350ee61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgeArea',
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('area_cod')
    )
    op.create_index(op.f('ix_knowledgeArea_name'), 'knowledgeArea', ['name'], unique=True)
    op.create_table('universityDegree',
    sa.Column('university_cod', sa.String(length=64), nullable=False),
    sa.Column('acronym', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('study_center', sa.String(length=64), nullable=True),
    sa.Column('plan_cod', sa.String(length=64), nullable=True),
    sa.Column('special_cod', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('university_cod')
    )
    op.create_index(op.f('ix_universityDegree_acronym'), 'universityDegree', ['acronym'], unique=True)
    op.create_index(op.f('ix_universityDegree_name'), 'universityDegree', ['name'], unique=True)
    op.create_table('teacher',
    sa.Column('dni', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surnames', sa.String(length=64), nullable=True),
    sa.Column('area_cod', sa.String(length=64), nullable=True),
    sa.Column('potential', sa.String(length=64), nullable=True),
    sa.Column('tutorial_hours', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['area_cod'], ['knowledgeArea.area_cod'], ),
    sa.PrimaryKeyConstraint('dni')
    )
    op.create_table('subject',
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('university_cod', sa.String(length=64), nullable=True),
    sa.Column('coordinator_dni', sa.String(length=64), nullable=True),
    sa.Column('responsible_dni', sa.String(length=64), nullable=True),
    sa.Column('academic_year', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('semester', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['area_cod'], ['knowledgeArea.area_cod'], ),
    sa.ForeignKeyConstraint(['coordinator_dni'], ['teacher.dni'], ),
    sa.ForeignKeyConstraint(['responsible_dni'], ['teacher.dni'], ),
    sa.ForeignKeyConstraint(['university_cod'], ['universityDegree.university_cod'], ),
    sa.PrimaryKeyConstraint('subject_cod', 'area_cod')
    )
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=True),
    sa.Column('first_semester', sa.String(length=128), nullable=True),
    sa.Column('second_semester', sa.String(length=128), nullable=True),
    sa.Column('hours', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorial_teacher_dni'), 'tutorial', ['teacher_dni'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_user_teacher_dni'), 'user', ['teacher_dni'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('veniaI',
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['area_cod'], ['knowledgeArea.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('area_cod', 'teacher_dni')
    )
    op.create_table('PDA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('observations', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['subject_cod', 'area_cod'], ['subject.subject_cod', 'subject.area_cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('group_cod', sa.String(length=64), nullable=False),
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('hours', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['subject_cod', 'area_cod'], ['subject.subject_cod', 'subject.area_cod'], ),
    sa.PrimaryKeyConstraint('group_cod', 'subject_cod', 'area_cod')
    )
    op.create_table('veniaII',
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['subject_cod', 'area_cod'], ['subject.subject_cod', 'subject.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('subject_cod', 'area_cod', 'teacher_dni')
    )
    op.create_table('impart',
    sa.Column('group_cod', sa.String(length=64), nullable=False),
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=False),
    sa.Column('hours', sa.String(length=64), nullable=True),
    sa.Column('state_solicitation', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['group_cod', 'subject_cod', 'area_cod'], ['group.group_cod', 'group.subject_cod', 'group.area_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('group_cod', 'subject_cod', 'area_cod', 'teacher_dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impart')
    op.drop_table('veniaII')
    op.drop_table('group')
    op.drop_table('PDA')
    op.drop_table('veniaI')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_teacher_dni'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tutorial_teacher_dni'), table_name='tutorial')
    op.drop_table('tutorial')
    op.drop_table('subject')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_universityDegree_name'), table_name='universityDegree')
    op.drop_index(op.f('ix_universityDegree_acronym'), table_name='universityDegree')
    op.drop_table('universityDegree')
    op.drop_index(op.f('ix_knowledgeArea_name'), table_name='knowledgeArea')
    op.drop_table('knowledgeArea')
    # ### end Alembic commands ###
