"""empty message

Revision ID: f2d06b4b898f
Revises: 53410fc4979d
Create Date: 2019-06-23 14:34:17.145113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d06b4b898f'
down_revision = '53410fc4979d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impart',
    sa.Column('group_cod', sa.String(length=64), nullable=False),
    sa.Column('subject_cod', sa.String(length=64), nullable=False),
    sa.Column('area_cod', sa.String(length=64), nullable=False),
    sa.Column('teacher_dni', sa.String(length=64), nullable=False),
    sa.Column('hours', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['group_cod', 'subject_cod', 'area_cod'], ['group.group_cod', 'group.subject_cod', 'group.subject_cod'], ),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teacher.dni'], ),
    sa.PrimaryKeyConstraint('group_cod', 'subject_cod', 'area_cod', 'teacher_dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impart')
    # ### end Alembic commands ###
