"""empty message

Revision ID: fcdf847f2b33
Revises: 05ed8bb95b86
Create Date: 2019-04-29 20:37:46.789019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdf847f2b33'
down_revision = '05ed8bb95b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura_area',
    sa.Column('cod_asig', sa.Integer(), nullable=True),
    sa.Column('cod_area', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cod_area'], ['areasconocimiento.cod_area'], ),
    sa.ForeignKeyConstraint(['cod_asig'], ['asignatura.cod_asignatura'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignatura_area')
    # ### end Alembic commands ###
